# Error Handling

本节介绍Rust的异常处理机制。

## 编译器错误

Rust中的部分错误可以在编译时被检测出来，这些错误被称为编译时错误（compile-time error）。使用`rustc --explain`可以查看编译时错误的详细信息。

```bash
rustc --explain E0382
# A variable was used after its contents were moved elsewhere.
#
# Erroneous code example:
#
# struct MyStruct { s: u32 }
#
# fn main() {
#    let mut x = MyStruct { s: 5u32 };
#    let y = x;
#    x.s = 6;
#    println!("{}", x.s);
# }
# ...
```

## 异常（Panic）

Rust中的异常被称为panic。当程序发生panic时，Rust会打印出异常信息并退出程序。有多个宏可以用于触发异常。

```rust
// 以下的宏也可以接受类似println!的格式化字符串
panic!("This is a panic!");
unimplemented!(); // 用于标记未实现的代码
unreachable!(); // 用于标记不可能到达的分支

// 以下宏用于测试
assert!(false); // 用于测试表达式是否为true
assert_eq!(1, 2); // 用于测试两个表达式的值是否相等
assert_ne!(1, 1); // 用于测试两个表达式的值是否不相等

// 在Debug模式或使用-C debug-assertions参数时，以下宏才会触发
debug_assert!(false);
debug_assert_eq!(1, 2);
debug_assert_ne!(1, 1);
```

## 异常处理

Rust中内置了两个类型`Option<T>`和`Result<T, E>`用于异常处理，其定义为

```rust
enum Option<T> {
    None,
    Some(T),
}
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

以下，均以`T`代表`Option::Some`或`Result::Ok`的类型，`E`代表`Result::Err`的类型。

* `Option`类型用于表示一个可能不存在的值，常用于函数参数、结构体字段或函数返回值，使用`match`语句可以匹配`Option`类型取值的不同情况。

    ```rust
    fn main() {
        let x: Option<i32> = Some(5);
        match x {
            Some(i) => println!("{}", i),
            None => println!("None"),
        }
    }
    ```

    1. 使用`is_some`和`is_none`方法可以快速判断`Option`类型是否为`Some`或`None`。
    2. 使用`unwrap`方法可以将`Option`类型转换为`T`类型，如果`Option`类型为`None`，则会触发异常。

* `Result`类型用于表示一个可能出错的值，常用于函数返回值。`Ok`表示函数执行成功，`Err`表示函数执行失败。

    ```rust
    fn main() {
        let x: Result<i32, &str> = Ok(5);
        match x {
            Ok(i) => println!("{}", i),
            Err(e) => println!("{}", e),
        }
    }
    ```

    1. 使用`is_ok`和`is_err`方法可以快速判断`Result`类型是否为`Ok`或`Err`。
    2. 使用`ok`和`err`方法可以将`Result<T, E>`类型转换为`Option<T>`类型。如果调用的方法和`Result`类型的取值相同，则返回`Some(T)`，否则返回`None`。

        ```rust
        fn main() {
            let x: Result<i32, &str> = Ok(5);
            let y: Option<i32> = x.ok();
            println!("{:?}", y); // Some(5)
            let x: Result<i32, &str> = Err("error");
            let y: Option<i32> = x.ok();
            println!("{:?}", y); // None
        }
        ```

    3. 使用`unwrap`方法或`expect`方法可以将`Result`类型转换为`T`类型，如果`Result`类型为`Err`，则会触发异常，输出的异常信息对应于`Err`中的值或`expect`方法的参数。

        ```rust
        fn main() {
            let x: Result<i32, &str> = Ok(5);
            let y: i32 = x.unwrap();
            println!("{}", y); // 5
            let x: Result<i32, &str> = Err("error");
            let y: i32 = x.unwrap(); // thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "error"', src/main.rs:2:26
            println!("{}", y);
        }
        ```

`unwrap`方法有如下变种：

* `expect`方法，接受一个字符串作为参数，用于指定跳出异常时的提示信息。
* （仅`Result`类型）`unwrap_err`方法和`expect_err`方法，与`unwrap`相反，当`Result`类型为`Ok`时，会触发异常，否则返回`Err`中的值。
* `unwrap_or`方法，接受一个`T`类型的参数，在`unwrap`方法会触发异常的情况下，返回该参数。
* `unwrap_or_default`方法，在`unwrap`方法会触发异常的情况下，返回该默认值。该方法要求`T`类型实现了`Default`特性。

    ```rust
    struct MyStruct {
        s: i32
    }

    fn main() {
        let a: Option<MyStruct> = None;
        println!("{}", a.unwrap_or_default().s);
        // error[E0277]: the trait bound `MyStruct: Default` is not satisfied
    }
    ```

* `unwrap_or_else`方法，接受一个函数作为参数，在`unwrap`方法会触发异常的情况下，返回函数的返回值。其中，`Result`类型的闭包参数为`E`类型，`Option`类型的闭包参数为`()`类型，函数的返回值需要和`Some`或`Ok`的类型相同。

    ```rust
    fn increment(x: i32) -> i32 {
        x + 1
    }

    fn main() {
        let a: Result<i32, i32> = Err(2);
        println!("{}", a.unwrap_or_else(increment));
        // 3
    }
    ```

### 运算

Rust可以在不取出`Option`或`Result`类型的值的情况下，对其进行运算。对于以下方法，记`A`为调用方法的对象，`B`为方法的参数，即`A.method(B)`。

!!! note "`Option`和`Result`的真值"

    不妨将`Option`和`Result`类型的`Some`和`Ok`视为**真**，其中的值`T`称为**真值**，`None`和`Err`视为**假**，`Err`的值`E`视为**假值**。

1. 逻辑运算`A.or(B)`与`A.and(B)`方法，接受一个和自身类型相同的参数。
    * 对于`or()`，如果`A`为真，则返回`A`的真值，否则返回`B`值。
    * 对于`and()`，如果`A`为假，则返回`A`的假值，否则返回`B`。
2. `A.or_else()`为`A.or(B)`的变种，接受一个函数作为参数。如果为真，则返回`A`的真值，否则返回函数的返回值。
3. `A.and_then()`为`A.and(B)`的变种，接受一个函数作为参数。如果为假，则返回`A`的假值，否则返回函数的返回值。
4. （仅`Option`类型）`A.filter()`，接受一个函数`fn (T) -> bool`作为参数。如果`A`为真，且以其真值作为参数后调用函数返回真，则返回`A`的真值，否则返回`None`。
5. `A.map()`，接受一个函数`fn (T) -> U`作为参数。如果`A`为真，则返回`A`的真值作为参数后调用函数的返回值，否则返回`A`的假值。注意返回值的类型为`Option<U>`或`Result<U, E>`。
    * （仅`Result`类型）`A.map_err()`，接受一个函数`fn (E) -> F`作为参数。如果`A`为假，则返回`A`的假值作为参数后调用函数的返回值，否则返回`A`的真值。
    * （仅`Option`类型）`A.map_or()`，接受一个`U`类型的默认值和一个函数`fn (T) -> U`作为参数。如果`A`为真，则返回`A`的真值作为参数后调用函数的返回值，否则返回默认值。
    * `A.map_or_else()`，接受一个函数`fn () -> U`和一个函数`fn (T) -> U`作为参数。如果`A`为真，则返回`A`的真值作为参数后调用第二个函数的返回值，否则返回第一个函数的返回值。
6. （仅`Option`类型）`A.ok_or()`用于将`Option`类型转换为`Result`类型，接受一个`E`类型的参数。如果`A`为真，则返回`A`的真值，否则返回参数作为`Err`的值。
    * `A.ok_or_else()`为`A.ok_or()`的变种，接受一个函数作为参数。如果`A`为真，则返回`A`的真值，否则返回函数的返回值。
7. `A.as_ref()`和`A.as_mut()`，用于将`Option<T>`或`Result<T, E>`类型转换其对应的引用。其中`A.as_ref()`返回不可变引用，即`Option<&T>`或`Result<&T, &E>`；`A.as_mut()`返回可变引用，即`Option<&mut T>`或`Result<&mut T, &mut E>`。

## 异常传递

Rust中，有两种方式可以向上返回异常。

* `?`运算符，用于将`Option`或`Result`类型转换为`T`类型，如果`Result`类型为`Err`或，则会直接返回`Err`中的值。

    ```rust
    fn fn_with_error<'a>() -> Result<i32, &'a str> {
        Err("Deterministic error")
    }
    fn use_fn<'a>() -> Result<i32, &'a str> {
        let x = fn_with_error()?; // Directly return Err("Deterministic error")
        Ok(x) // unreachable
    }
    fn main() {
        let x: &str = use_fn().unwrap_err();
        println!("{}", x); // Deterministic error
    }
    ```

* `try!`宏，与`?`的效果等同，使用方式为`try!(expression)`。目前已经被弃用，使用`?`代替。

    ```rust
    fn fn_with_error<'a>() -> Result<i32, &'a str> {
        Err("Deterministic error")
    }
    fn use_fn<'a>() -> Result<i32, &'a str> {
        let x = try!(fn_with_error()); // error: use of deprecated `try` macro
        Ok(x) // unreachable
    }
    fn main() {
        let x: &str = use_fn().unwrap_err();
        println!("{}", x); // Deterministic error
    }
    ```

### 主函数

Rust的`main`函数只能取`()`或`Result<(), E>`类型，其中`E`为`std::error::Error`的实现类型。如果`main`函数返回`Result`类型，则会将`Err`中的值打印到`stderr`并退出程序。

```rust
use std::fs::File;

fn main() -> std::io::Result<()> {
    let _ = File::open("not-existing-file.txt")?; // Result::Err

    Ok(()) // Default return value
    // Must with this line, otherwise return () which is incompatible
}
```

如果`main`函数的返回值类型不是`()`或`Result`，则无法通过编译。

```rust
fn main() -> i32 {
    0
}
// error[E0277]: `main` has invalid return type `i32`
```

## 自定义异常

在Rust中可以自定义异常类型。异常类型需要实现`std::error::Error`特性，该特性定义了以下方法：

* `fn source(&self) -> Option<&(dyn Error + 'static)>`，用于返回引起异常的原因（可选）。
* `fn Debug::fmt(&self, f: &mut Formatter<'_>) -> Result`，用于格式化异常信息（用于调试）。
* `fn Display::fmt(&self, f: &mut Formatter<'_>) -> Result`，用于格式化异常信息（用于输出）。

{% raw %}
```rust linenums="1" hl_lines="16"
struct MyError {
    code: i32,
    message: String
}

impl std::error::Error for MyError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        None
    }
}

impl std::fmt::Debug for MyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f, "MyError {{ code: {}, message: {} }} at file {} line {}",
            self.code, self.message, file!(), line!()
            // file!() and line!() are macros to get the current file and line
        )
    }
}

impl std::fmt::Display for MyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "MyError {{ code: {}, message: {} }}", self.code, self.message)
    }
}

// Use the error

fn raise_error() -> Result<(), MyError> {
    Err(MyError { code: 1, message: "Error message".to_string() })
}

fn main() -> Result<(), MyError> {
    let _ = raise_error()?;
    // MyError { code: 1, message: Error message } at file src/main.rs line 16
    Ok(())
}
```
{% endraw %}

### 异常转换

由于Rust中的异常类型是静态的，因此在异常传递过程中，可能会遇到异常类型不匹配的情况。此时，可以使用`From`特性将异常类型转换为另一种异常类型。

以下以`std::io::Error`为例。

```rust
impl std::convert::From<std::io::Error> for MyError {
    fn from(error: std::io::Error) -> Self {
        MyError { code: 2, message: error.to_string() }
    }
}
```

此后，无需显式调用`From`特性的方法，即可将`std::io::Error`类型转换为`MyError`类型。
